### ISSUE TITLE
Version numbering scheme makes scoop miss updates in some cases

### ISSUE THREAD

**Issue by arpsmack** [Ash258/Scoop-JetBrains#42] opened 2021-07-02 19:04 UTC
I tried to update Intellij-IDEA today from `2021.1-211.6693.111` to `2021.1.3-211.7628.21` but scoop kept claiming I was on the latest version.

Scoop compares these version numbers by splitting on '.' and '-' and then numerically comparing each component in order, but because the newer version adds a new component, it compares less than the previous version:

```
Old version: [ 2021, 1, 211, 6693,  111     ]
New version: [ 2021, 1,   3,  211, 7628, 21 ]
                          ^
                          \- 211 > 3 so it stops here
```

This confuses scoop into thinking the newer version is actually older.

It could probably be avoided by always including the implicit `.0`: `2021.1.0-211.6693.111` (or I suppose by persuading scoop to change how they compare versions).

**Comment by Ash258** [comment] 2021-07-02 19:07
Duplicate of lukesampson/scoop#2720

**Closed by Ash258** 2021-07-02 19:07 UTC
