### ISSUE TITLE
Rider-Portable `2020.2.1` not detected for update

### ISSUE THREAD

**Issue by turnertime** [Ash258/Scoop-JetBrains#24] opened 2020-08-26 17:37 UTC
Rider-portable version `2020.2.1` is sorted before `2020.2` with scoop's [sort-version](https://github.com/lukesampson/scoop/blob/3d8d5e84c34f185e901e52aba4d94226ad05981c/lib/versions.ps1) which results in `update` not detecting that version. This can be resolved by including the `patch` (`.0`) in the version number. For example, from `2020.2-202.6397.244` to `2020.2.0-202.6397.244`.

**Comment by Ash258** [comment] 2020-08-26 18:06
Stop posting not relevant and already known issues about base scoop here... Next time you open issue in wrong repo you will be blocked.

Duplicate of lukesampson/scoop#4081, lukesampson/scoop#3721

**Closed by Ash258** 2020-08-26 18:06 UTC
